---
- name: ensure cgroup is correctly mounted
  sudo: true
  mount: src=cgroup name=/sys/fs/cgroup fstype=cgroup opts=defaults dump=0 passno=0 state=mounted

- name: check if live-debconfig exists
  shell: "[ -f /usr/share/lxc/packages/live-debconfig_4.0~alpha31-1_all.deb ] && echo 'true' || echo 'false'"
  register: package_exist

- name: add live-debconfig source
  sudo: true
  apt_repository: repo='deb http://ftp.lt.debian.org/debian unstable main contrib non-free' state=present update_cache=yes
  when: package_exist.stdout == 'false'

- name: download the package
  sudo: true
  shell: apt-get download live-debconfig chdir=/usr/share/lxc/packages creates=/usr/share/lxc/packages/live-debconfig_4.0~alpha31-1_all.deb
  when: package_exist.stdout == 'false'

- name: update lxc to less buggy version
  sudo: true
  apt: pkg=lxc state=latest
  when: package_exist.stdout == 'false'

- name: remove live-debconfig source
  sudo: true
  apt_repository: repo='deb http://ftp.lt.debian.org/debian unstable main contrib non-free' state=absent update_cache=yes
  when: package_exist.stdout == 'false'

- name: enable ip packet forwarding permanently
  sudo: true
  lineinfile: dest=/etc/sysctl.conf regexp='#?net.ipv4.ip_forward=.*' line='net.ipv4.ip_forward=1' state=present

- name: enable ip packet forwarding for current session
  sudo: true
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

