---
- name: ensure dependancies are installed
  debug: msg="yes"

- name: ensure cgroup is correctly mounted
  sudo: true
  mount: src=cgroup name=/sys/fs/cgroup fstype=cgroup opts=defaults dump=0 passno=0 state=mounted

